### ISSUE TITLE
Linphone-desktop built Error  in MAC Catalina : IOError: [Errno 2] No such file or directory: '-DUNIX64'

### ISSUE THREAD

**Issue by Omid-Mohajerani** [BelledonneCommunications/linphone-desktop#359]
Hi,

I have this error when I'm building in my MAC OS Catalina. Any idea on how to solve this error is appreciated. 

Or is there anyway to exclude this codec and continue build without it ? 

<img width="704" alt="Screenshot 2020-05-04 at 1 06 28 AM" src="https://user-images.githubusercontent.com/5101364/80920614-847a1380-8da3-11ea-8818-3e6b79999e6e.png">

[ 74%] Performing build step for 'EP_openh264'
Traceback (most recent call last):
  File "/usr/local/bin/nasm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/nasm/console.py", line 8, in main
    with open(sys.argv[1]) as f:
IOError: [Errno 2] No such file or directory: '-DUNIX64'
make[9]: *** [codec/common/x86/cpuid.o] Error 1
make[8]: *** [/Users/omidmohajerani/Downloads/linphone-mac/2/linphone-desktop/WORK/WORK/desktop/Stamp/EP_openh264/EP_openh264-build] Error 2
make[7]: *** [CMakeFiles/EP_openh264.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [sdk-prefix/src/sdk-stamp/sdk-build] Error 2
make[4]: *** [CMakeFiles/sdk.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [WORK/stamp/sdk-build] Error 2
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
make: *** [all] Error 2

**Comment by Omid-Mohajerani** [comment]
ok I got it myself and documented here on how to build .. 

http://omid-mohajerani.blogspot.com/


Actually one simple method is to use cmake-gui  command
