### ISSUE TITLE
Crash when quitting (segfault)

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#549]
**Describe the bug**
When quitting Linphone, the terminal shows that a crash occured:

> [17:16:11:805][0x1557f90][Info]"Destroying app..."
> Speicherzugriffsfehler (Speicherabzug geschrieben)
> (roughly translatable as "Memory access error (Memory dump written)")

**To Reproduce**
1. Start Linphone
2. Click the Tray icon > Quit
3. See the error on the terminal

**Expected behavior**
No crash when exiting.

**Desktop:**
 - OS: Ubuntu 20.04
 - Version inphone-4.3.0-beta.51+daa56cc7.AppImage
 - Version of the SDK [e.g 4.4.9]

The crash already occured with `Linphone-4.3.0-beta.38+ed52503e`.

**Strack trace**
Not very helpful because the appimage misses the debugging symbols:
```
Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
0x00007ffff5f36ec9 in ?? () from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5

(gdb) bt
#0  0x00007ffff5f36ec9 in ?? () from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
#1  0x00007ffff5ec5265 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
#2  0x00007ffff5ea27fb in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
#3  0x00007ffff5eb7aac in QQmlType::SingletonInstanceInfo::init(QQmlEngine*) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
#4  0x00007ffff5dc555b in QV4::QQmlContextWrapper::getPropertyAndBase(QV4::QQmlContextWrapper const*, QV4::PropertyKey, QV4::Value const*, bool*, QV4::Value*, QV4::Lookup*) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
#5  0x00007ffff5dc58e8 in QV4::QQmlContextWrapper::resolveQmlContextPropertyLookupGetter(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value*) () from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
#6  0x00007fffa1c3e1a6 in ?? ()
#7  0x0000000000000000 in ?? ()

(gdb) bt full
#0  0x00007ffff5f36ec9 in ?? () from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#1  0x00007ffff5ec5265 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#2  0x00007ffff5ea27fb in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#3  0x00007ffff5eb7aac in QQmlType::SingletonInstanceInfo::init(QQmlEngine*) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#4  0x00007ffff5dc555b in QV4::QQmlContextWrapper::getPropertyAndBase(QV4::QQmlContextWrapper const*, QV4::PropertyKey, QV4::Value const*, bool*, QV4::Value*, QV4::Lookup*) ()
   from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#5  0x00007ffff5dc58e8 in QV4::QQmlContextWrapper::resolveQmlContextPropertyLookupGetter(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value*) () from /tmp/.mount_LinphoOFONbV/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#6  0x00007fffa1c3e1a6 in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by cweiske** [comment]
I can confirm it's fixed with beta 63.
