### ISSUE TITLE
Crash when quitting because of language change (segfault)

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#558]
**Describe the bug**
When opening Preferences > User Interface and changing the Language, a popup asks to restart linphone:

> It is necessary to restart the application.
> Do you want to restart now?
> Confirm

When doing that, Linphone quits and crashes:

> Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.

**To Reproduce**
1. Open Preferences
2. User Interface
3. Change Language
4. Confirm
5. Linphone crashes

**Expected behavior**
Linphone should not crash but restart.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 4.3.0 AppImage (final)
 - Version of the SDK: Desktop 4.3.0 - Qt5.12.5, Core 5.0.39

**SDK logs**
```
Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
0x00007ffff5f3dec9 in ?? () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5

(gdb) bt
#0  0x00007ffff5f3dec9 in ?? () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
#1  0x00007ffff5ecc265 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
#2  0x00007ffff5ea97fb in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
#3  0x00007ffff5ebeaac in QQmlType::SingletonInstanceInfo::init(QQmlEngine*) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
#4  0x00007ffff5dcc55b in QV4::QQmlContextWrapper::getPropertyAndBase(QV4::QQmlContextWrapper const*, QV4::PropertyKey, QV4::Value const*, bool*, QV4::Value*, QV4::Lookup*) ()
   from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
#5  0x00007ffff5dcc8e8 in QV4::QQmlContextWrapper::resolveQmlContextPropertyLookupGetter(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value*) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
#6  0x00007fffb3859426 in ?? ()
#7  0x0000000000000000 in ?? ()

(gdb) bt full
#0  0x00007ffff5f3dec9 in ?? () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#1  0x00007ffff5ecc265 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#2  0x00007ffff5ea97fb in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#3  0x00007ffff5ebeaac in QQmlType::SingletonInstanceInfo::init(QQmlEngine*) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#4  0x00007ffff5dcc55b in QV4::QQmlContextWrapper::getPropertyAndBase(QV4::QQmlContextWrapper const*, QV4::PropertyKey, QV4::Value const*, bool*, QV4::Value*, QV4::Lookup*) ()
   from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#5  0x00007ffff5dcc8e8 in QV4::QQmlContextWrapper::resolveQmlContextPropertyLookupGetter(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value*) () from /tmp/.mount_LinphoceBJ0x/usr/bin/../lib/libQt5Qml.so.5
No symbol table info available.
#6  0x00007fffb3859426 in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by julonexus** [comment]
I guess this is because of Qt 5.12.5. I'm on Qt 5.12.11 and I didn't reproduce it (fedora 34).
I'll confirm that for Qt 5.12.5

**Comment by julonexus** [comment]
I confirm. Updating to Qt 5.12.11 fix it.

**Comment by julonexus** [comment]
Next versions will be build with Qt 5.12.12

**Comment by cweiske** [comment]
Works fine with LinPhone 4.3.2 (Appimage)
