### ISSUE TITLE
Python error when compile linphone-desktop

### ISSUE THREAD

**Issue by robingarbo** [BelledonneCommunications/linphone-desktop#565]
Here is my issue:
i'm compile with 
cmake --build . --target install

[  5%] Performing install step for 'EP_srtp'
make[9]: avertissement : jobserver n'est pas disponible : utilisation de -j1. Ajouter « + » à la règle parent du make.
[ 33%] Built target generatorCommonCode
[100%] Built target speexdsp
Traceback (most recent call last):
  File "/home/user/.local/bin/nasm", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/nasm/console.py", line 8, in main
    with open(sys.argv[1]) as f:
FileNotFoundError: [Errno 2] No such file or directory: '-I/home/user/Apps/linphone-desktop/build/WORK/WORK/desktop/Build/turbojpeg'
make[11]: *** [simd/CMakeFiles/simd.dir/build.make:80: simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o] Error 1
make[10]: *** [CMakeFiles/Makefile2:343: simd/CMakeFiles/simd.dir/all] Error 2
make[9]: *** [Makefile:136: all] Error 2
make[8]: *** [CMakeFiles/EP_turbojpeg.dir/build.make:88: /home/user/Apps/linphone-desktop/build/WORK/WORK/desktop/Stamp/EP_turbojpeg/EP_turbojpeg-build] Error 2
make[7]: *** [CMakeFiles/Makefile2:489: CMakeFiles/EP_turbojpeg.dir/all] Error 2
make[7]: *** Attente des tâches non terminées....

**Comment by soroshsabz** [comment]
ITNOA

related to #608
related to #607
related to #647 
related to #652
related to #604
