### ISSUE TITLE
[Bug]: Crash when quitting linphone

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#588]
### Context

I use Linphone to receive calls from other people on my PC.

### General information

- Device: Custom-built Desktop PC
- OS: Ubuntu Linux 20.04
- Version of the App: Linphone-4.3.2.AppImage
- Version of the SDK: Desktop 4.3.2 - Qt5.12.12, Core 5.0.49

### Expected behaviour

I wanted to exit Linphone on the desktop by clicking the tray icon and selecting "Quit".
In the terminal, I see that Linphone crashes.

This only happens when I received a call. The crash does not happen when I start Linphone and quit without receiving a call in between.

### To Reproduce

1. Start Linphone
2. Receive a call
3. Quit Linphone
4. Terminal shows a crash (SIGSEGV)

### Additional context

First lines of stack trace:
```
Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff332be43 in has_type (id=39, obj=<optimized out>)
    at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_object.c:31
#2  belle_sip_object_cast (id=39, castname=<optimized out>, 
    file=<optimized out>, fileno=143, obj=<optimized out>)
    at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_object.c:479
```
[linphone-quit-call-crash.log](https://github.com/BelledonneCommunications/linphone-desktop/files/7693733/linphone-quit-call-crash.log)

**Comment by cweiske** [comment]
Happened today with Linphone-4.4.0-beta.46+49eb29fe

**Comment by cweiske** [comment]
Happened today with Linphone-4.4.1.

Does not seem to happen with Linphone 4.4.2 anymore.
