### ISSUE TITLE
[Bug]: crush with ICE candidates

### ISSUE THREAD

**Issue by sergey-safarov** [BelledonneCommunications/linphone-desktop#694]
### Context

I make test calls when the ICE feature is enabled.
As a result Linphone was crushed.

### General information

- Device: Dell 7373
- OS: Fedora 33
- Version of the App: Linphone-4.4.0-beta.58+0bc88e40.AppImage
- Version of the SDK: Linphone-4.4.0-beta.58+0bc88e40.AppImage

### Expected behaviour

Linphone is able to negotiate with ICE candidates.

### To Reproduce

1. enable ICE on Linphone side;
2. make a call to the server with ICE support.

### Additional context

Linphone logs attached
[linphone1.log](https://github.com/BelledonneCommunications/linphone-desktop/files/9439529/linphone1.log)

GDB backtrace
```
(gdb) set pagination off
(gdb) bt full
#0  0x00007ffff4ed2403 in ice_find_candidate_with_same_foundation (c1=0x5727a30, c2=0x0) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:3298
No locals.
#1  0x00007ffff7d8983a in bctbx_list_find_custom (list=0x51acc00, compare_func=<optimized out>, user_data=<optimized out>) at ../../../../../../../linphone-sdk/bctoolbox/src/containers/list.c:225
No locals.
#2  0x00007ffff4ecc48d in ice_compute_candidate_foundation (candidate=0x0, cl=0x51e26e0) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:3307
        l = <optimized out>
        other_candidate = <optimized out>
#3  ice_discover_peer_reflexive_candidate (cl=<optimized out>, pair=0x5c73ae0, msg=0x67f6750) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:2380
        taddr_str = "84.201.199.47:62477", '\000' <repeats 44 times>
        xor_mapped_address = <optimized out>
        taddr = {ip = "84.201.199.47", '\000' <repeats 50 times>, port = 62477, family = 2}
        elem = <optimized out>
        candidate = 0x0
        taci = {ta = <optimized out>, componentID = <optimized out>}
#4  ice_handle_received_binding_response (cl=<optimized out>, rtp_session=<optimized out>, evt_data=<optimized out>, msg=0x67f6750, remote_addr=<optimized out>) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:2771
        tr_id_str = "c0bb5b42e645c0a363e7c63e"
        tr_id = {octet = {<optimized out> <repeats 12 times>}}
        elem = <optimized out>
        tr = <optimized out>
        succeeded_pair = 0x5c73ae0
        candidate = <optimized out>
        valid_pair = <optimized out>
#5  ice_handle_stun_packet (cl=<optimized out>, rtp_session=0x224d390, evt_data=<optimized out>) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:2946
        source_addr_str = "3.101.84.15:24759", '\000' <repeats 46 times>
        recv_addr_str = "192.168.122.1:7079", '\000' <repeats 45 times>
        tr_id_str = "c0bb5b42e645c0a363e7c63e"
        recv_addrlen = <optimized out>
        mp = <optimized out>
        msg = 0x67f6750
        tr_id = {octet = {<optimized out> <repeats 12 times>}}
        source_stun_addr = {ip = {v4 = {port = <optimized out>, addr = <optimized out>}, v6 = {port = <optimized out>, addr = {octet = {<optimized out> <repeats 16 times>}}}}, family = <optimized out>}
        recv_addr = {ss_family = <optimized out>, __ss_padding = {<optimized out> <repeats 118 times>}, __ss_align = <optimized out>}
#6  0x00007ffff4ed4031 in media_stream_iterate (stream=<optimized out>) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/mediastream.c:445
        evt = <optimized out>
        ev = 0x7fff84008eb0
        curtime = <optimized out>
#7  0x00007ffff594dbc5 in LinphonePrivate::MS2Stream::handleEvents (this=0x1d40b30) at ../../../../../../../linphone-sdk/liblinphone/src/conference/session/ms2-stream.cpp:1197
        ms = 0x1d3f6b0
        ev = <optimized out>
#8  0x00007ffff594f1d9 in LinphonePrivate::MS2Stream::startEventHandling()::$_5::operator()() const (this=<optimized out>) at ../../../../../../../linphone-sdk/liblinphone/src/conference/session/ms2-stream.cpp:935
No locals.
#9  std::_Function_handler<bool (), LinphonePrivate::MS2Stream::startEventHandling()::$_5>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1716
No locals.
#10 0x00007ffff2fe8f9b in std::function<bool ()>::operator()() const (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127
No locals.
#11 cpp_timer_func (ud=0x5727a30, events=0) at ../../../../../../../linphone-sdk/belle-sip/src/cpp_utils.cc:96
        func = <optimized out>
        ret = <optimized out>
#12 0x00007ffff2e6c6d9 in belle_sip_main_loop_iterate (ml=<optimized out>) at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_loop.c:697
        s = 0x5c051a0
        pfd_size = <optimized out>
        duration = <optimized out>
        i = <optimized out>
        tmp_pool = <optimized out>
        can_clean = <optimized out>
        elem = 0x64755a0
        next = 0x64755a0
        to_be_notified = <optimized out>
        it = <optimized out>
        cur = <optimized out>
        ret = <optimized out>
        end = <optimized out>
        pfd = <optimized out>
        s = <optimized out>
        next_wakeup_time = <optimized out>
        diff = <optimized out>
        revents = <optimized out>
        s = <optimized out>
        expire = <optimized out>
        s = <optimized out>
        s = <optimized out>
        objdesc = <optimized out>
#13 belle_sip_main_loop_run (ml=<optimized out>) at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_loop.c:753
No locals.
#14 0x00007ffff2e6c99f in belle_sip_main_loop_sleep (ml=0x1631d80, milliseconds=0) at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_loop.c:766
        s = <optimized out>
#15 0x00007ffff5b60f52 in LinphonePrivate::Sal::iterate (this=0x0) at ../../../../../../../linphone-sdk/liblinphone/src/sal/sal.h:137
No locals.
#16 linphone_core_iterate (lc=0x160a1e0) at ../../../../../../../linphone-sdk/liblinphone/coreapi/linphonecore.c:4112
        curtime_ms = <optimized out>
        one_second_elapsed = true
        current_real_time = 1661684426
        diff_time = <optimized out>
#17 0x00000000005b3814 in CoreManager::iterate (this=0xee6b10) at /builds/BC/public/linphone-desktop/linphone-app/src/components/core/CoreManager.cpp:398
No locals.
#18 0x00007ffff48ce8bb in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#19 0x00007ffff48db1e7 in QTimer::timeout(QTimer::QPrivateSignal) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff48db4d8 in QTimer::timerEvent(QTimerEvent*) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#21 0x00007ffff48cf45b in QObject::event(QEvent*) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#22 0x00007ffff6c9de7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Widgets.so.5
No symbol table info available.
#23 0x00007ffff6ca4f44 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007ffff48a1bd8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#25 0x00007ffff48f8d89 in QTimerInfoList::activateTimers() () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#26 0x00007ffff48f9531 in ?? () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#27 0x00007fffec16e7f7 in g_main_context_dispatch () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libglib-2.0.so.0
No symbol table info available.
#28 0x00007fffec16ea60 in ?? () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libglib-2.0.so.0
No symbol table info available.
#29 0x00007fffec16eb0c in g_main_context_iteration () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libglib-2.0.so.0
No symbol table info available.
#30 0x00007ffff48f98af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#31 0x00007ffff48a05ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#32 0x00007ffff48a8ee0 in QCoreApplication::exec() () from /tmp/.mount_LinphoKXaLT4/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#33 0x00000000004d58dd in main (argc=<optimized out>, argv=<optimized out>) at /builds/BC/public/linphone-desktop/linphone-app/src/app/main.cpp:75
        controller = {mApp = <optimized out>}
        app = <optimized out>
        ret = <optimized out>
        enabler = {<No data fields>}
        core = Python Exception <class 'gdb.error'> value has been optimized out: 
```

**Comment by julonexus** [comment]
Hi
I suggest to test with the last version ( https://download.linphone.org/snapshots/linux/app/Linphone-4.5.0-alpha.300+9524833e.AppImage )

**Comment by sergey-safarov** [comment]
issue still reproduced
```
(gdb) bt full
#0  0x00007ffff4d8d003 in ice_find_candidate_with_same_foundation (c1=0x6349420, c2=0x0) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:3324
No locals.
#1  0x00007ffff7d87aca in bctbx_list_find_custom (list=0x5467180, compare_func=<optimized out>, user_data=<optimized out>) at ../../../../../../../linphone-sdk/bctoolbox/src/containers/list.c:225
No locals.
#2  0x00007ffff4d871e8 in ice_compute_candidate_foundation (candidate=0x0, cl=0x6521f50) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:3333
        l = <optimized out>
        other_candidate = <optimized out>
#3  ice_discover_peer_reflexive_candidate (cl=<optimized out>, pair=0x6f51be0, msg=0x7fff800014d0) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:2393
        taddr_str = "84.201.194.48:59953", '\000' <repeats 44 times>
        xor_mapped_address = <optimized out>
        taddr = {ip = {<optimized out> <repeats 64 times>}, port = <optimized out>, family = <optimized out>}
        elem = <optimized out>
        candidate = 0x0
        taci = {ta = <optimized out>, componentID = <optimized out>}
#4  ice_handle_received_binding_response (cl=<optimized out>, rtp_session=<optimized out>, evt_data=<optimized out>, msg=0x7fff800014d0, remote_addr=<optimized out>) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:2791
        tr_id_str = "dc3ede4200fcafd108c931d0"
        tr_id = {octet = {<optimized out> <repeats 12 times>}}
        elem = <optimized out>
        tr = <optimized out>
        succeeded_pair = 0x6f51be0
        candidate = <optimized out>
        valid_pair = <optimized out>
#5  ice_handle_stun_packet (cl=<optimized out>, rtp_session=0x62c8000, evt_data=<optimized out>) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/ice.c:2967
        source_addr_str = "3.101.84.126:31293", '\000' <repeats 45 times>
        recv_addr_str = "192.168.122.1:55823", '\000' <repeats 44 times>
        tr_id_str = "dc3ede4200fcafd108c931d0"
        recv_addrlen = <optimized out>
        mp = <optimized out>
        msg = 0x7fff800014d0
        tr_id = {octet = {<optimized out> <repeats 12 times>}}
        source_stun_addr = {ip = {v4 = {port = <optimized out>, addr = <optimized out>}, v6 = {port = <optimized out>, addr = {octet = {<optimized out> <repeats 16 times>}}}}, family = <optimized out>}
        recv_addr = {ss_family = <optimized out>, __ss_padding = {<optimized out> <repeats 118 times>}, __ss_align = <optimized out>}
#6  0x00007ffff4d8ec31 in media_stream_iterate (stream=<optimized out>) at ../../../../../../../linphone-sdk/mediastreamer2/src/voip/mediastream.c:443
        evt = <optimized out>
        ev = 0x7fff800069c0
        curtime = <optimized out>
#7  0x00007ffff58b4f65 in LinphonePrivate::MS2Stream::handleEvents (this=0x65a7ac0) at ../../../../../../../linphone-sdk/liblinphone/src/conference/session/ms2-stream.cpp:1257
        ms = 0x223b8b0
        ev = <optimized out>
#8  0x00007ffff58b6899 in LinphonePrivate::MS2Stream::startEventHandling()::$_5::operator()() const (this=<optimized out>) at ../../../../../../../linphone-sdk/liblinphone/src/conference/session/ms2-stream.cpp:985
No locals.
#9  std::_Function_handler<bool (), LinphonePrivate::MS2Stream::startEventHandling()::$_5>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1716
No locals.
#10 0x00007ffff2e6c0fb in std::function<bool ()>::operator()() const (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127
No locals.
#11 cpp_timer_func (ud=0x6349420, events=0) at ../../../../../../../linphone-sdk/belle-sip/src/cpp_utils.cc:96
        func = <optimized out>
        ret = <optimized out>
#12 0x00007ffff2cf2bb9 in belle_sip_main_loop_iterate (ml=<optimized out>) at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_loop.c:697
        s = 0x7a21b00
        pfd_size = <optimized out>
        duration = <optimized out>
        i = <optimized out>
        tmp_pool = <optimized out>
        can_clean = <optimized out>
        elem = 0x66b0600
        next = 0x66b0600
        to_be_notified = <optimized out>
        it = <optimized out>
        cur = <optimized out>
        ret = <optimized out>
        end = <optimized out>
        pfd = <optimized out>
        s = <optimized out>
        next_wakeup_time = <optimized out>
        diff = <optimized out>
        revents = <optimized out>
        s = <optimized out>
        expire = <optimized out>
        s = <optimized out>
        s = <optimized out>
        objdesc = <optimized out>
#13 belle_sip_main_loop_run (ml=<optimized out>) at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_loop.c:753
No locals.
#14 0x00007ffff2cf2e7f in belle_sip_main_loop_sleep (ml=0x1544460, milliseconds=0) at ../../../../../../../linphone-sdk/belle-sip/src/belle_sip_loop.c:766
        s = <optimized out>
#15 0x00007ffff5af93f2 in LinphonePrivate::Sal::iterate (this=0x0) at ../../../../../../../linphone-sdk/liblinphone/src/sal/sal.h:139
No locals.
#16 linphone_core_iterate (lc=0x1526ed0) at ../../../../../../../linphone-sdk/liblinphone/coreapi/linphonecore.c:4158
        curtime_ms = <optimized out>
        one_second_elapsed = true
        current_real_time = 1664539276
        diff_time = <optimized out>
#17 0x00000000005fe064 in CoreManager::iterate (this=0x13b7dd0) at /builds/BC/public/linphone-desktop/linphone-app/src/components/core/CoreManager.cpp:416
No locals.
#18 0x00007ffff47538bb in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#19 0x00007ffff47601e7 in QTimer::timeout(QTimer::QPrivateSignal) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff47604d8 in QTimer::timerEvent(QTimerEvent*) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#21 0x00007ffff475445b in QObject::event(QEvent*) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#22 0x00007ffff7134e7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Widgets.so.5
No symbol table info available.
#23 0x00007ffff713bf44 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007ffff4726bd8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#25 0x00007ffff477dd89 in QTimerInfoList::activateTimers() () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#26 0x00007ffff477e569 in ?? () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#27 0x00007fffebfdc7f7 in g_main_context_dispatch () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libglib-2.0.so.0
No symbol table info available.
#28 0x00007fffebfdca60 in ?? () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libglib-2.0.so.0
No symbol table info available.
#29 0x00007fffebfdcb0c in g_main_context_iteration () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libglib-2.0.so.0
No symbol table info available.
#30 0x00007ffff477e8af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#31 0x00007ffff47255ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#32 0x00007ffff472dee0 in QCoreApplication::exec() () from /tmp/.mount_LinphoxP80v9/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#33 0x00000000004f024d in main (argc=<optimized out>, argv=<optimized out>) at /builds/BC/public/linphone-desktop/linphone-app/src/app/main.cpp:75
        controller = {mApp = <optimized out>}
        app = <optimized out>
        ret = <optimized out>
        enabler = {<No data fields>}
```

and log 
[linphone1-20220930.log](https://github.com/BelledonneCommunications/linphone-desktop/files/9683942/linphone1-20220930.log)
